server:
  port: 8081

## mybaits
spring:
  datasource:
    schema: classpath:import.sql

mybatis:
  mapperLocations: classpath:mappers/*Mapper.xml
  typeAliasesPackage: cn.hykes.boot.domain

appender:
  console:
    type: Console
    name: console
    layout:
      type: PatternLayout

rootLogger:
  level: info
  appenderRef:
    console:
      ref: console

#hbs
hbs:
  root: /Users/hehaiyang/GitHub/spring-boot-examples/src/main/resources/statics
  prefix: ${hbs.root}
  suffix: .hbs